spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username : sa
    password : 123
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug